development:
  adapter: postgresql
  host: localhost
  database: little-league-development
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

